<a href="https://colab.research.google.com/github/nisarg1782/mlp-programs/blob/main/kneighbours_university.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder,MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier

In [3]:
data=pd.read_csv("iris.csv")
data.head(2)

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa

In [4]:
x=data.drop("variety",axis=1)
x.head(2)

sepal.length  sepal.width  petal.length  petal.width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2

In [5]:
from sklearn.model_selection import train_test_split

In [7]:
lb=LabelEncoder()
y=lb.fit_transform(data["variety"])

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)


In [9]:
kn=KNeighborsClassifier(n_neighbors=4,metric="minkowski")

In [10]:
kn.fit(x_train,y_train)


KNeighborsClassifier(n_neighbors=4)

In [11]:
kn.predict([[4.9,3.0,1.4,0.2]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([0])

In [12]:
y_pred=kn.predict(x_test)
y_pred

array([2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 1, 0, 1, 0, 2, 2, 2, 1, 2, 0,
       0, 1, 1, 1, 1, 0, 1, 2])

In [14]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [15]:
confusion_matrix(y_test,y_pred)

array([[ 7,  0,  0],
       [ 0,  9,  2],
       [ 0,  0, 12]])

In [16]:
accuracy_score(y_test,y_pred)

0.9333333333333333