<a href="https://colab.research.google.com/github/nisarg1782/mlp-programs/blob/main/lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
matrix=np.arange(1,10).reshape(3,3)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
matrix2=np.arange(11,20).reshape(3,3)
matrix2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [7]:
matrix4=np.hstack((matrix,matrix2))
matrix4

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [8]:
matrix5=np.vstack((matrix,matrix2))
matrix5

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [10]:
matrix6=np.vstack((matrix4,matrix5))
matrix6

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 6 and the array at index 1 has size 3