<a href="https://colab.research.google.com/github/nisarg1782/mlp-programs/blob/main/numpy_university.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
one_dim=np.array([1,2,3])
one_dim.ndim

1

In [29]:
two_dim=np.array([[1,2,3],[4,5,6]],dtype="str")
two_dim.itemsize


4

In [3]:
one_dim.max()

3

In [4]:
one_dim.dtype

dtype('int64')

In [7]:
one_dim.itemsize

8

In [8]:
two_dim.item

<function ndarray.item>

In [10]:
matrix0=np.zeros((2,2))
matrix0

array([[0., 0.],
       [0., 0.]])

In [11]:
matrix1=np.ones((3,3))
matrix1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
mat1=np.arange(1,10).reshape(3,3)
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
mat2=np.arange(11,20).reshape(3,3)
mat2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [14]:
mat_sum=mat1+mat2
mat_sub=mat1-mat2
mat_mul=mat1*mat2
mat_div=mat1/mat2


In [15]:
mat_sum

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [17]:
mat_vstack=np.vstack((mat_sum,mat_sub))

In [18]:
mat_vstack

array([[ 12,  14,  16],
       [ 18,  20,  22],
       [ 24,  26,  28],
       [-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [19]:
mat_hstack=np.hstack((mat_sum,mat_sub))
mat_hstack

array([[ 12,  14,  16, -10, -10, -10],
       [ 18,  20,  22, -10, -10, -10],
       [ 24,  26,  28, -10, -10, -10]])

In [22]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [23]:
mat_vsplit=np.vsplit(mat_vstack,[1,3,5])


In [25]:
mat_vsplit[0]

array([[12, 14, 16]])

In [27]:
mat_hsplit=np.hsplit(mat_hstack,[1,2,3,8])
mat_hsplit

[array([[12],
        [18],
        [24]]),
 array([[14],
        [20],
        [26]]),
 array([[16],
        [22],
        [28]]),
 array([[-10, -10, -10],
        [-10, -10, -10],
        [-10, -10, -10]]),
 array([], shape=(3, 0), dtype=int64)]