<a href="https://colab.research.google.com/github/nisarg1782/mlp-programs/blob/main/numpy_uni.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
one_dim=np.array([1,2,3])
one_dim

array([1, 2, 3])

In [ ]:
two_dim=np.array([[1,2,3],[4,5,6]])

In [ ]:
two_dim.shape

(2, 3)

In [ ]:
two_dim[0][1]

2

In [ ]:
np.max(two_dim)


6

In [ ]:
two_dim.itemsize

8

In [ ]:
two_dim.min

<function ndarray.min>

In [ ]:
np.std(two_dim)

1.707825127659933

In [ ]:
np.sort(two_dim,ascending=False)

TypeError: sort() got an unexpected keyword argument 'ascending'

In [ ]:
one_array=np.ones((3,3))

In [ ]:
one_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
zeeros=np.zeros((2,2))

In [ ]:
zeeros

array([[0., 0.],
       [0., 0.]])

In [ ]:
matrix1=np.arange(1,10).reshape(3,3)

In [ ]:
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrix2=np.arange(11,20).reshape(3,3)
matrix2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
matrix_sum=matrix1+matrix2
matrix_sum

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [ ]:
matrix_sub=matrix1-matrix2
matrix_sub

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [ ]:
matrix_mul=matrix1*matrix2

In [ ]:
matrix_mul


array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [ ]:
matrix_vstack=np.vstack((matrix1,matrix2))
matrix_vstack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
matrixhstack=np.hstack((matrix1,matrix2))
matrixhstack

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [ ]:
matrix_vsplit=np.vsplit(matrix_vstack,[1,3,5])


In [ ]:
matrix_vsplit

[array([[1, 2, 3]]),
 array([[4, 5, 6],
        [7, 8, 9]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[17, 18, 19]])]

In [ ]:
matrix_hsplit=np.hsplit(matrixhstack,[1,3,5,8])
matrix_hsplit

[array([[1],
        [4],
        [7]]),
 array([[2, 3],
        [5, 6],
        [8, 9]]),
 array([[11, 12],
        [14, 15],
        [17, 18]]),
 array([[13],
        [16],
        [19]]),
 array([], shape=(3, 0), dtype=int64)]