<a href="https://colab.research.google.com/github/nisarg1782/mlp-programs/blob/main/numpy_29_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [46]:
onedim=np.array([1,2,3],dtype=str)
onedim

array(['1', '2', '3'], dtype='<U1')

In [49]:
onedim.dtype
onedim.itemsize

4

In [4]:
two_dim=np.array([[1,2,3],[4,5,6]])
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
two_dim.dtype

dtype('int64')

In [6]:
two_dim.itemsize

8

In [7]:
two_dim.astype

<function ndarray.astype>

In [11]:
x=two_dim.sum()
x

21

In [12]:
two_dim.std()

1.707825127659933

In [14]:
zeros=np.zeros((2,2))

In [15]:
zeros

array([[0., 0.],
       [0., 0.]])

In [16]:
one_ar=np.ones((2,2))
one_ar

array([[1., 1.],
       [1., 1.]])

In [17]:
matrix1=np.arange(1,10).reshape(3,3)
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
matrix2=np.arange(11,20).reshape(3,3)
matrix2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [20]:
matrix_sum=matrix1+matrix2
matrix_sum

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [22]:
matrix_sub=matrix1-matrix2
matrix_sub

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [23]:
matrix_mul=matrix1*matrix2

In [24]:
matrix_mul

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [25]:
matrix_div=matrix1/matrix2

In [26]:
matrix_div

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [27]:
matrix_vstack=np.vstack((matrix1,matrix2))
matrix_vstack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [28]:
matrix_hstack=np.hstack((matrix1,matrix2))
matrix_hstack

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [29]:
matrix_vsplit=np.vsplit(matrix_vstack,(1,3,5))
matrix_vsplit

[array([[1, 2, 3]]),
 array([[4, 5, 6],
        [7, 8, 9]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[17, 18, 19]])]

In [31]:
matrix_hsplit=np.hsplit(matrix_hstack,(1,3,5))
matrix_hsplit

[array([[1],
        [4],
        [7]]),
 array([[2, 3],
        [5, 6],
        [8, 9]]),
 array([[11, 12],
        [14, 15],
        [17, 18]]),
 array([[13],
        [16],
        [19]])]

In [35]:
matix_line=np.linspace(1,10,2)
matix_line

array([ 1., 10.])

In [37]:
matrix1.dtype

dtype('int64')

In [38]:
matrix1.itemsize

8

In [39]:
matrix1.max()

9

In [41]:
matrix1.size

9

In [42]:
matrix1.ndim

2

In [45]:
matrix1.shape

(3, 3)