<a href="https://colab.research.google.com/github/nisarg1782/mlp-programs/blob/main/numpy_revsion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
import numpy as np

In [2]:
onedim_array=np.array([1,2,3])
onedim_array

array([1, 2, 3])

In [3]:
twodim_array=np.array([[1,2,3],[4,5,6]])
twodim_array

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
threedim_array=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
threedim_array

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [5]:
threedim_array.shape

(1, 3, 3)

In [7]:
threedim_array.size

9

In [8]:
threedim_array.itemsize

8

In [12]:
threedim_array.dtype

dtype('int64')

In [13]:
threedim_array.ndim

3

In [19]:
matrix0=np.zeros((3,3))

In [20]:
matrix0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
matrix1=np.ones((2,2))
matrix1

array([[1., 1.],
       [1., 1.]])

In [24]:
matrix1[::]

array([[1., 1.],
       [1., 1.]])

In [26]:
matrix1.dtype


dtype('float64')

In [27]:
matrix1.ndim

2

In [28]:
matrix1[0][0]=2

In [29]:
matrix1

array([[2., 1.],
       [1., 1.]])

In [32]:
matrix1[0][0]=1

In [33]:
matrix1[0][0]

1.0

In [34]:
twodim_array

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
twodim_array[0][0]='a'

ValueError: invalid literal for int() with base 10: 'a'

In [37]:
twodim_array[0][0]

1

In [38]:
twodim_array.astype

<function ndarray.astype>

In [39]:
matrix3=np.arange(1,10)

In [40]:
matrix3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
matrix4=np.arange(1,10).reshape(3,3)

In [42]:
matrix4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
matrix5=np.arange(11,20).reshape(3,3)
matrix5

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [46]:
matrix6=matrix5/matrix4
matrix6

array([[11.        ,  6.        ,  4.33333333],
       [ 3.5       ,  3.        ,  2.66666667],
       [ 2.42857143,  2.25      ,  2.11111111]])

In [49]:
matrixvstack=np.vstack((matrix5,matrix6))
matrixvstack

array([[11.        , 12.        , 13.        ],
       [14.        , 15.        , 16.        ],
       [17.        , 18.        , 19.        ],
       [11.        ,  6.        ,  4.33333333],
       [ 3.5       ,  3.        ,  2.66666667],
       [ 2.42857143,  2.25      ,  2.11111111]])

In [68]:
matrixhstack=np.hstack((matrix5,matrix6))

In [51]:
matrixhstack

array([[11.        , 12.        , 13.        , 11.        ,  6.        ,
         4.33333333],
       [14.        , 15.        , 16.        ,  3.5       ,  3.        ,
         2.66666667],
       [17.        , 18.        , 19.        ,  2.42857143,  2.25      ,
         2.11111111]])

In [55]:
matrix_linespace=np.linspace(1,10,2)
matrix_linespace

array([ 1., 10.])

In [66]:
mat10=np.vsplit(matrixvstack,(1,3,4,5,6))
mat10


[array([[11., 12., 13.]]),
 array([[14., 15., 16.],
        [17., 18., 19.]]),
 array([[11.        ,  6.        ,  4.33333333]]),
 array([[3.5       , 3.        , 2.66666667]]),
 array([[2.42857143, 2.25      , 2.11111111]]),
 array([], shape=(0, 3), dtype=float64)]

In [69]:
matrixhstack

array([[11.        , 12.        , 13.        , 11.        ,  6.        ,
         4.33333333],
       [14.        , 15.        , 16.        ,  3.5       ,  3.        ,
         2.66666667],
       [17.        , 18.        , 19.        ,  2.42857143,  2.25      ,
         2.11111111]])

In [71]:
mat11=np.hsplit(matrixhstack,(1,4,6,8))
mat11

[array([[11.],
        [14.],
        [17.]]),
 array([[12.        , 13.        , 11.        ],
        [15.        , 16.        ,  3.5       ],
        [18.        , 19.        ,  2.42857143]]),
 array([[6.        , 4.33333333],
        [3.        , 2.66666667],
        [2.25      , 2.11111111]]),
 array([], shape=(3, 0), dtype=float64),
 array([], shape=(3, 0), dtype=float64)]